---
name: Test

on:
  push:

jobs:
  test:
    name: test
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install libnetcdff-dev gfortran

      - name: Link appropriate make configuration
        run: cd src && ln -s gcc_pkgconfig.mk current.mk

      - name: Create binaries (no fimex)
        run: cd src && env SNAP_DEBUG_CHECKS=1 make -j2

      - name: Clean up
        run: cd src && make clean

      - name: Install official fimex-binary from launchpad
        run: |
            sudo add-apt-repository -y ppa:met-norway/fimex
            sudo apt update
            sudo apt install libfimex-1.6-dev

      - name: Create binaries (with fimex)
        run: cd src && make clean && env SNAP_FIMEX_VERSION=1.6 SNAP_DEBUG_CHECKS=1 make -j2

      - name: Install test requirements
        run: sudo apt-get install python3-numpy python3-netcdf4

      - name: Test binaries
        run: cd src && env SNAP_FIMEX_VERSION=1.6 SNAP_DEBUG_CHECKS=1 make test
